service: cloudwatch-alarm

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-northeast-1

functions:
  target: # 監視対象の Lambda 関数
    handler: target.handler
  watcher: # 監視する Lambda 関数（ Slack への通知を行う）
    handler: watcher.handler
    environment: # Slack の設定（デプロイ後に変更できるように環境変数にしてある）
      SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZZZZZZZZZZZZZ'
      SLACK_WEBHOOK_CHANNEL: '#random'
      SLACK_WEBHOOK_USERNAME: 'ALERT WATCHER'
      SLACK_WEBHOOK_ICON_EMOJI: ':sos:'
    events:
      - sns: cloudwatch-alarm-notifyer # 監視対象の Lambda のエラー通知を受ける SNS のトピック

# CloudWatch alarm のリソースの定義
# see http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
resources:
  Resources:
    Notifyer:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: notifyer
        Namespace: 'AWS/Lambda'
        MetricName: Errors
        Threshold: 1.0
        Statistic: Minimum
        Period: 60
        EvaluationPeriods: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - Name: FunctionName
            Value: 'cloudwatch-alarm-dev-target' # 監視対象の Lambda 関数の関数名（`${サービス名}-${ステージ名}-${関数名}`)
        AlarmActions:
          - Ref: SNSTopicCloudwatchalarmnotifyer # アラームが発生した時に呼び出す SNS （ `SNSTopic${キャピタライズして記号を除いたトピック名}`）
        AlarmDescription: 'An error occurred'
